---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-case-conflict
        stages: ['commit']
      - id: check-executables-have-shebangs
        stages: ['commit']
      - id: check-json
        stages: ['commit']
      - id: check-merge-conflict
        stages: ['commit']
      - id: check-symlinks
        stages: ['commit']
      - id: check-toml
        stages: ['commit']
      - id: check-xml
        stages: ['commit']
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
        stages: ['commit']
      - id: destroyed-symlinks
        stages: ['commit']
      - id: detect-private-key
        stages: ['commit']
      - id: end-of-file-fixer
        stages: ['commit']
        exclude: "^(.*/)?cmdline.txt$"
      - id: fix-byte-order-marker
        stages: ['commit']
      - id: mixed-line-ending
        stages: ['commit']
      - id: trailing-whitespace
        stages: ['commit']

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.0.2
    hooks:
      - id: ansible-lint
        exclude: .pre-commit-config.yaml
        stages: ['commit']

  - repo: https://git.iamthefij.com/iamthefij/ansible-pre-commit.git
    rev: v0.1.2
    hooks:
      - id: encryption-check
        stages: ['commit']

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs.git
    rev: v1.1.2
    hooks:
      - id: markdown-toc
        stages: ['commit']
