---

- name: Préparation de la SD Card Raspberry PI d'un robot
  hosts: localhost
  connection: local

  vars:
    raspberry_pi_download:
      url: https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip
      sha256: c5dad159a2775c687e9281b1a0e586f7471690ae28f2f2282c90e7d59f64273c

  vars_prompt:
    - name: sd_card_device
      prompt: SD Card device
      default: /dev/mmcblk0
      private: false

    - name: sd_card_partition_prefix
      prompt: SD Card prefixe de partition
      default: p
      private: false

    - name: restore_img
      prompt: Restauration sur la SD Card
      default: true
      private: false

    - name: force_hdmi
      prompt: Configuration pour force la sortie HDMI
      default: false
      private: false

    - name: hostname
      prompt: Hostname
      private: false

  tasks:
    - name: Inclusion des variables
      include_vars:
        file: vars/wifi.vault.yaml

    - name: Création répertoire de download
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - .tmp
        - .mnt
        - .mnt/boot
        - .mnt/root

    - name: Contrôle téléchargement nécéssaire
      stat:
        path: ".tmp/{{ raspberry_pi_download.url | basename }}"
        checksum_algorithm: sha256
      register: raspberry_pi_info

    - name: Download image d'installation Raspberry PI
      get_url:
        url: "{{ raspberry_pi_download.url }}"
        dest: .tmp/
        checksum: "sha256:{{ raspberry_pi_download.sha256 }}"
      when: not raspberry_pi_info.stat.exists or raspberry_pi_info.stat.checksum != raspberry_pi_download.sha256

    - name: Contrôle unarchive déjà effectué
      stat:
        path: ".tmp/{{ raspberry_pi_download.url | basename | replace('.zip','.img') }}"
      register: unarchive_info

    - name: Unzip image Rapsberry PI
      unarchive:
        src: ".tmp/{{ raspberry_pi_download.url | basename }}"
        dest: .tmp/
      when: not unarchive_info.stat.exists

    - name: "Restore Image sur la SD Card {{ sd_card_device }}"
      command: "dd if=.tmp/{{ raspberry_pi_download.url | basename | replace('.zip','.img') }} of={{ sd_card_device }}"
      when: restore_img | bool
      become: true

    - name: Montage de la partition SD Card
      mount:
        boot: false
        src: "{{ sd_card_device }}{{ item.partition }}"
        path: "{{ item.path }}"
        fstype: "{{ item.fstype }}"
        state: mounted
      with_items:
        - partition: "{{ sd_card_partition_prefix }}1"
          path: .mnt/boot
          fstype: vfat
        - partition: "{{ sd_card_partition_prefix }}2"
          path: .mnt/root
          fstype: ext4
      become: true

    - name: Création du répertoire SSH de pi
      file:
        path: .mnt/root/home/pi/.ssh
        state: directory
        owner: 1000
        group: 1000
        mode: 0700
      become: true

    - name: Templates de configuration
      template:
        src: "templates/{{ item }}"
        dest: ".mnt/{{ item }}"
      with_items:
        - boot/wpa_supplicant.conf
        - boot/ssh
        - root/etc/default/keyboard
        - root/etc/hostname
        - root/home/pi/.ssh/authorized_keys
      become: true

    - name: Configuration hostname
      replace:
        path: .mnt/root/etc/hosts
        regexp: 'raspberrypi'
        replace: '{{hostname}}'
      become: true

    - name: Configuration HDMI
      replace:
        path: .mnt/boot/config.txt
        regexp: '^#(hdmi_force_hotplug|hdmi_drive)'
        replace: '\1'
      when: force_hdmi | bool
      become: true

    - name: Configuration SSH
      lineinfile:
        path: .mnt/root/etc/ssh/ssh_config
        line: "IPQoS cs0 cs0"
        state: present
      become: true

    - name: Configuration pour la connexion SSH de pi
      file:
        path: .mnt/root/home/pi/.ssh/authorized_keys
        mode: 0600
        owner: 1000
        group: 1000
      become: true

    - name: Demontage de la partition SD Card
      mount:
        path: "{{ item }}"
        state: absent
      with_items:
        - .mnt/boot
        - .mnt/root
      become: true
