---

- name: Préparation de la SD Card Raspberry PI d'un robot
  hosts: localhost
  connection: local

  vars:
    raspberry_pi_download:
      buster:
        url: https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-05-28/2021-05-07-raspios-buster-arm64-lite.zip
        sha256: 868cca691a75e4280c878eb6944d95e9789fa5f4bbce2c84060d4c39d057a042

      bullseye:
        url: https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2022-01-28/2022-01-28-raspios-bullseye-arm64-lite.zip
        sha256: d694d2838018cf0d152fe81031dba83182cee79f785c033844b520d222ac12f5

  vars_prompt:
    - name: sd_card_device
      prompt: SD Card device
      default: /dev/sda
      private: false

    - name: sd_card_partition_prefix
      prompt: SD Card prefixe de partition
      private: false

    - name: restore_img
      prompt: Restauration sur la SD Card
      default: true
      private: false

    - name: hostname
      prompt: Hostname
      private: false

    - name: os_code_name
      prompt: Code name de la version de Raspi OS (bullseye ou buster)
      default: buster
      private: false

  tasks:
    - name: Inclusion des variables
      include_vars:
        file: vars/wifi.vault.yaml

    - name: Création répertoire de download
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - .tmp
        - .mnt
        - .mnt/boot
        - .mnt/root

    - name: Contrôle téléchargement nécéssaire
      stat:
        path: ".tmp/{{ raspberry_pi_download[os_code_name].url | basename }}"
        checksum_algorithm: sha256
      register: raspberry_pi_info

    - name: Download image d'installation Raspberry PI
      get_url:
        url: "{{ raspberry_pi_download[os_code_name].url }}"
        dest: .tmp/
        checksum: "sha256:{{ raspberry_pi_download[os_code_name].sha256 }}"
      when: not raspberry_pi_info.stat.exists or raspberry_pi_info.stat.checksum != raspberry_pi_download[os_code_name].sha256

    - name: Contrôle unarchive déjà effectué
      stat:
        path: ".tmp/{{ raspberry_pi_download[os_code_name].url | basename | replace('.zip','.img') }}"
      register: unarchive_info

    - name: Unzip image Rapsberry PI
      unarchive:
        src: ".tmp/{{ raspberry_pi_download[os_code_name].url | basename }}"
        dest: .tmp/
      when: not unarchive_info.stat.exists

    - name: "Restore Image sur la SD Card {{ sd_card_device }}"
      command: "dd if=.tmp/{{ raspberry_pi_download[os_code_name].url | basename | replace('.zip','.img') }} of={{ sd_card_device }}"
      when: restore_img | bool
      become: true

    - name: Montage de la partition SD Card # noqa: syntax-check[unknown-module]
      mount:
        boot: false
        src: "{{ sd_card_device }}{{ item.partition }}"
        path: "{{ item.path }}"
        fstype: "{{ item.fstype }}"
        state: mounted
      with_items:
        - partition: "{{ sd_card_partition_prefix }}1"
          path: .mnt/boot
          fstype: vfat
        - partition: "{{ sd_card_partition_prefix }}2"
          path: .mnt/root
          fstype: ext4
      become: true

    - name: Création du répertoire SSH de pi
      file:
        path: .mnt/root/home/pi/.ssh
        state: directory
        owner: 1000
        group: 1000
        mode: 0700
      become: true

    - name: Templates de configuration
      template:
        src: "templates/{{ item }}"
        dest: ".mnt/{{ item }}"
      with_items:
        - boot/wpa_supplicant.conf
        - boot/ssh
        - root/etc/default/keyboard
        - root/etc/hostname
        - root/home/pi/.ssh/authorized_keys
      become: true

    - name: Configuration hostname
      replace:
        path: .mnt/root/etc/hosts
        regexp: 'raspberrypi'
        replace: '{{hostname}}'
      become: true

    - name: Check fichier conf SSH exist
      stat:
        path: .mnt/root/etc/ssh/ssh_config
      register: ssh_config_stat

    - name: Configuration SSH
      lineinfile:
        path: .mnt/root/etc/ssh/ssh_config
        line: "IPQoS cs0 cs0"
        state: present
      when: ssh_config_stat.stat.exists
      become: true

    - name: Configuration pour la connexion SSH de pi
      file:
        path: .mnt/root/home/pi/.ssh/authorized_keys
        mode: 0600
        owner: 1000
        group: 1000
      become: true

    - name: Demontage de la partition SD Card
      mount:
        path: "{{ item }}"
        state: absent
      with_items:
        - .mnt/boot
        - .mnt/root
      become: true
