---

all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      connection: local
    nerell:
      ansible_host: 192.168.0.1
    elfa:
      ansible_host: 192.168.0.2
    balise_vision:
      ansible_host: 192.168.0.3
