---

all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      connection: local
    nerell: []
    odin: []
    tinker: []
    pami-triangle: []
    pami-carre: []
    pami-rond: []

  children:
    robots:
      hosts:
        nerell: []
        odin: []
        
    pamis:
      hosts:
        pami-triangle: []
        pami-carre: []
        pami-rond: []
