---

all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      connection: local
    odin: []
    nerell: []
    tinker: []

  children:
    robots:
      hosts:
        nerell: []
        odin: []
