---

all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      connection: local
    nerell:
      ansible_host: nerell.local
    odin:
      ansible_host: odin.local
    tinker:
      ansible_host: tinker.local
    pami-triangle:
      ansible_host: pami-triangle.local
    pami-carre:
      ansible_host: pami-carre.local
    pami-rond:
      ansible_host: pami-rond.local

  children:
    robots:
      hosts:
        nerell: []
        odin: []

    pamis:
      hosts:
        pami-triangle: []
        pami-carre: []
        pami-rond: []
        pami-star: []
