---

# Repository par défaut
arig_common_apt_repositories:
  buster:
    - deb-src http://deb.debian.org/debian buster main contrib non-free
    - deb-src http://deb.debian.org/debian-security/ buster/updates main contrib non-free
    - deb-src http://deb.debian.org/debian buster-updates main contrib non-free

  bullseye:
    - deb-src http://deb.debian.org/debian bullseye main contrib non-free
    - deb-src http://security.debian.org/debian-security bullseye-security main contrib non-free
    - deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free

arig_common_java_downloads:
  - url: https://download.bell-sw.com/java/17.0.11+10/bellsoft-jre17.0.11+10-linux-aarch64.tar.gz
    sha1: 6fff17c19690b89def564cdef6e50631069c6e47
  - url: https://download.bell-sw.com/java/18.0.1+12/bellsoft-jre18.0.1+12-linux-aarch64.tar.gz
    sha1: 7b7f430ec282a3cc284e5ec60dace83bf7e7904d
  - url: https://download.bell-sw.com/java/21.0.3+10/bellsoft-jre21.0.3+10-linux-aarch64.tar.gz
    sha1: 8e199395a13b00f411388cada787636e1473f1e1
  - url: https://download.bell-sw.com/java/22.0.1+10/bellsoft-jre22.0.1+10-linux-aarch64.tar.gz
    sha1: 0b0142c5709c0a7a9a5a1d8915edbd624f593751

# Hook d'activation
arig_common_enable_qt: false
arig_common_enable_java: false

# Bootscreen wallpaper config
arig_common_bootscreen_wallpaper_reversed: false

# Configuration sur la Raspberry PI
arig_common_raspberry_pi_config: {}

# Configuration du boot config.txt
arig_common_raspberry_pi_boot_config: []

# Configuration de la command line de boot
arig_common_raspberry_pi_cmdline: undefined
