---
arig_common_enable_qt: true
arig_common_enable_java: true

arig_common_raspberry_pi_config:
  i2c: true
  spi: true
  can: true

arig_common_raspberry_pi_cmdline:
  buster: "console=serial0,115200 console=tty1 root={{ ansible_cmdline.root }} rootfstype=ext4 elevator=deadline fsck.repair=yes video=DSI-1:800x480M@60,rotate=0 rootwait quiet splash plymouth.ignore-serial-consoles"
  bullseye: "console=serial0,115200 console=tty1 root={{ ansible_cmdline.root }} rootfstype=ext4 fsck.repair=yes video=DSI-1:800x480M@60,rotate=0 rootwait quiet splash plymouth.ignore-serial-consoles"

arig_common_raspberry_pi_boot_config:
  - disable_splash=1
  - boot_delay=0
  - force_turbo=1
  - lcd_rotate=0
  - core_freq=500
  - core_freq_min=500
  - dtparam=i2c_arm_baudrate=110000
  - dtoverlay=disable-bt
  - dtoverlay=mcp251xfd,spi0-0,oscillator=40000000,interrupt=25
  # - gpu_mem=128

arig_robot_image_name: pamis
arig_robot_primary: false
arig_robot_with_screen: false
arig_robot_with_can: true

arig_common_udev_rules:
  - name: 99-ldlidar.rules
    rules:
      - 'KERNEL=="ttyUSB*", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", SYMLINK+="ldlidar"'
